### ISSUE TITLE
Collapse All / Expand All Buttons

### ISSUE THREAD

**Issue by ffleurey** [kevoree/kevoree-web-editor#65]
When loading large models it would be nice to have buttons to expand and collapse all nodes at once instead of doing it one by one.

**Comment by maxleiko** [comment]
@ffleurey  It's already the case, just hit **ctrl+a** and then **f**, and voilà.

**Comment by maxleiko** [comment]
Note that **f** is a toggle, so if you already have fold/unfolded nodes, you will just negate the state it's already in.

**Comment by ffleurey** [comment]
Thanks :-)
